### ISSUE TITLE
code is a spaghetti mess

### ISSUE THREAD

**Issue by sergray** [borisgribkov/Movies-search#2]
no modularity, everything is scattered in across two Python scripts, this is a road to the maintenance hell

Please split code into modules:
- db - will implement all DB operations as functions using sqlite3 (later can be refactored to use ORM such as sqlalchemy)
- data - load data from movie lens and import into DB
- search  - should contain implementation of recommendation system using scipy and numpy
- ui - should implement user interactions

**Comment by borisgribkov** [comment]
At the moment my code contains four modules: main with ui interactions, database creation using sqllite, recommendation scheme (numpy, scipy), all db requests are located in the separated db_request module.
